# Generated by Django 4.1.2 on 2022-12-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_comments_alter_post_dislikes_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
