# Generated by Django 4.1.2 on 2022-12-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
    ]
