# Generated by Django 4.1.5 on 2023-01-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='profileFollowing', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='postCategories', to='api.category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ctg_following',
            field=models.ManyToManyField(blank=True, related_name='categoriesFollowing', to='api.category'),
        ),
    ]
